### PR TITLE
odhcpd: change ignore interface tag from ignore to ignore6

### PR DESCRIPTION
**Pull request by Menion2k**
There are network setup where it would be required to turn off dhcpv4
and have dhcpv6 (and all the address autoconfiguration) enabled
An example is a full static ipv4 dual stack network, also an ipv4
relayed bridge with ipv6 relay. Having the tag "ignore" used by both
dnsmasq and odhcpd as interface ignore tag prevents the configuration
of such networks

Signed-off-by: Antonio Silverio <menion@gmail.com>

### CODE REVIEW

**Comment by dedeckeh** [comment]
NAK; see https://git.openwrt.org/?p=project/odhcpd.git;a=commitdiff;h=08a93676f4d3d13fa417a1f109b40d6c577dfb76

**Comment by Menion2k** [comment]
Note: the mentioned patch from openwrt git is not present in the github code

**Comment by dedeckeh** [comment]
No but surely you can swap to the openwrt git code ?

**Comment by Menion2k** [comment]
Sure, but my point was to the github code
Anyhow I guess sooner or later the github code will be aligned (or
deprecated), so I am fine
Bye

2018-04-13 13:31 GMT+02:00 Hans Dedecker <notifications@github.com>:

**Pull request closed without merging**
