### PR TITLE
Add support for DHCPv4-over-DHCPv6 (RFC 7341)

### PR DESCRIPTION
**Pull request by mikma**
This branch adds support for DHCPv4-over-DHCPv6 (DHCP 4o6) transport as specified in [RFC 7341](https://tools.ietf.org/html/rfc7341).

I have tested it with ISC dhclient-4.4.2-r1 on Alpine Linux 3.12.
DHCP 4o6 on dhclient is enabled by using the -4o6 option, and the following two commands can be used for testing:

```
touch leases4 && dhclient -d -4 -4o6 6767 -lf leases4 -pf pid4 eth1
touch leases6 && dhclient -d -6 -4o6 6767 -lf leases6 -pf pid6 eth1
```

For troubleshooting I have written a DHCPv4-over-DHCPv6 Wireshark dissector in lua: [dhcpv6_4o6.lua](https://gist.github.com/mikma/1ff4a24c6b267dadfed6a4cafe6b438b).

### CODE REVIEW

**Comment by dedeckeh** [comment]
LGTM will merge it in the next days; thx

**Comment by dedeckeh** [comment]
Patches pushed; thx again

**Comment by mikma** [comment]
Thanks for pushing and updating the OpenWrt package.

But I noticed that the full package fails to build on some architectures.
https://downloads.openwrt.org/snapshots/faillogs/x86_64/base/odhcpd/full/compile.txt

I have made a small bugfix in the following commit: https://github.com/mikma/openwrt-odhcpd/commit/994e29bf3f74a96f705708748e20818293b844f1

**Comment by dedeckeh** [comment]
Can you create a PR with a patch for this issue ?

**Comment by mikma** [comment]
OK, I have created PR #162.

**Pull request closed without merging**
